version: "3.2"
services:
  database:
    container_name: soccer-container
    image: mysql:8.0.22
    volumes:
      - ~/docker/mysql/soccer/etc/mysql/conf.d:/etc/mysql/conf.d:ro
      - ~/docker/mysql/soccer/var/lib/mysql:/var/lib/mysql
      - ~/docker/mysql/soccer/var/log/mysql:/var/log/mysql
    environment:
      - MYSQL_DATABASE=roddb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - "3306:3306"
    networks:
      - rod_env
#    Mac
#    platform: linux/amd64
  application:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://soccer-container:3306/roddb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - rod_env
networks:
  rod_env:
    driver: bridge
