spring:
  application:
    name: soccer
  datasource:
    url: jdbc:mysql://localhost:3306/roddb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      platform: mysql
      mode: always
      encoding: utf-8
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          lob:
            '[non_contextual_creation]': true
        '[format_sql]': true
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace
